#!/bin/sh
# (C) 2009 Michael Taht
# iptables rules for temporarily allowing incoming mail
# for exim and spam filters that callback the sending host
# We check incoming syn attempts against port 25
# against a whitelist generated by outgoing syns against 25

# It is a very good idea to have the size of the table 
# as insmodded be 2x the size of the maximum people you 
# email in a burst.
#       ip_list_tot=2000
#              Number of addresses remembered per table.

#       ip_pkt_list_tot=6
#              Number of packets per address remembered.
# If attacked by a spammer, you can 
#       echo -addr >/proc/net/xt_recent/goodmail
#       to remove addr from the goodmail list

# SECONDS is a reserved var in bash

seconds=3600 # reap anything over an hour old
limiter=16 # note this is (limiter/(ntp_servers*20))
# http://www.dyndns.com/support/kb/mailhop_filtering.html

# 
#    dyndns and all of isc and my test server
mxs="216.146.32.0/23 149.20.54.0/24 75.145.127.229/32"

# just me
#mxs="216.146.32.0/23 149.20.54.64/32 149.20.54.82/32 149.20.54.81/32"

iptables -F # for testing ONLY

(
iptables -X REAPER
iptables -X LIMITER
iptables -X IN_SMTP
iptables -X OUT_SMTP 
iptables -N LIMITER
iptables -N REAPER
iptables -N IN_SMTP
iptables -N OUT_SMTP
) 
#2> /dev/null > /dev/null

#No ipset kernel support on this box, sigh
#iptables -A IN_SMTP -m set --match-set whitemail -j ACCEPT 

for i in $mxs
do
iptables -A IN_SMTP -s $i -j ACCEPT
done

# Cope with exim

iptables -A IN_SMTP -m recent --name sentmail --rcheck -j ACCEPT
iptables -A IN_SMTP -j LOG 
iptables -A IN_SMTP -j DROP # should probably do unreachable but...

# Add outgoing email IPs to the goodmail
# list on outgoing emails. 
 
iptables  -A OUT_SMTP -p tcp \
          -m recent --name sentmail --set --rdest

# We could reap the table on a syn or fin

iptables -A REAPER -m recent --update --name sentmail --seconds $seconds --reap
iptables -A LIMITER -m statistic --mode nth --every $limiter -g REAPER

# Add these two to the existing chains

iptables -A INPUT -i eth0 -p tcp --dport 25,567 --syn -g IN_SMTP
iptables -A OUTPUT -o eth0 -p tcp --dport 25 --syn -g OUT_SMTP

# But with ntp generating regular output we could just do it there
# BUT: there seems to be no way to delete source addresses
# So at the moment the table will just fill up as a LIFO

iptables -A OUTPUT -p udp --dport 123 -g LIMITER
